services:
    avathar.bbguildffxiv.installer:
        class: avathar\bbguildffxiv\game\ffxiv_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguildffxiv.provider:
        class: avathar\bbguildffxiv\game\ffxiv_provider
        arguments:
            - '@avathar.bbguildffxiv.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
